const MAX_REQUESTS_IN_BATCH = 50
const MAX_MODIFY_OPERATIONS_IN_REQUEST = 10

const TICKET_OTHER_SOURCE_ID = '7da1e3be-06ba-4c9e-bba6-f97f278ac6e4'


module.exports = {
    MAX_REQUESTS_IN_BATCH,
    MAX_MODIFY_OPERATIONS_IN_REQUEST,
    TICKET_OTHER_SOURCE_ID,
}